version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"  # Web UI
      - "8020:8020"  # HDFS Service
    environment:
      - CLUSTER_NAME=myhadoopcluster
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./data:/mnt/local
    networks:
      - hadoop-net

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    hostname: datanode1
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode1-data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop-net

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    hostname: datanode2
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode2-data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop-net

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    hostname: datanode3
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode3-data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop-net

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:
  datanode3-data:

networks:
  hadoop-net:
    name: hadoop-net